version: "2"

services:
  scss-compile-fancy:
    image: "node:8"
    working_dir: /home/fancy/
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/fancy/
    command: bash -c "npm i --quiet --silent && npm run sass"
  scss-compile-theme:
    image: "node:8"
    working_dir: /home/fancy/
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/fancy/
    command: bash -c "npm i --quiet --silent && npm run local-sass"
  web-server:
    image: "node:8"
    working_dir: /home/fancy/
    environment:
      - NODE_ENV=development
    volumes:
      - .:/home/fancy/
    ports:
      - "8080:8080"
    command: bash -c "npm i --quiet --silent && npm run server"
